# Generated by Django 5.2.17 on 2026-10-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=255, verbose_name='Název fakulty')),
                ('faculty_abbrev', models.CharField(max_length=255, verbose_name='Zkratka fakulty')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
            ],
            options={
                'verbose_name': 'Fakulta',
                'verbose_name_plural': 'Fakulty',
                'ordering': ['id'],
            },
        ),
    ]
