# Generated by Django 5.2.17 on 2026-10-05 19:34

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Číslo turnusu')),
                ('capacity', models.PositiveIntegerField(default=95, verbose_name='Kapacita')),
                ('start_date', models.DateField(verbose_name='Začátek')),
                ('end_date', models.DateField(verbose_name='Konec')),
            ],
            options={
                'verbose_name': 'Turnus',
                'verbose_name_plural': 'Turnusy',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='BillingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='', max_length=255, verbose_name='Město')),
                ('street', models.CharField(blank=True, default='', max_length=255, verbose_name='Ulice')),
                ('postal_code', models.CharField(blank=True, default='', max_length=255, verbose_name='PSČ')),
                ('country', models.CharField(blank=True, default='', max_length=255, verbose_name='Země')),
                ('phone', models.CharField(blank=True, default='', max_length=255, verbose_name='Telefon')),
            ],
            options={
                'verbose_name': 'Fakturační údaje',
                'verbose_name_plural': 'Fakturační údaje',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Jméno')),
                ('surname', models.CharField(max_length=255, verbose_name='Příjmení')),
                ('name_normalized', models.CharField(blank=True, default='', max_length=255, verbose_name='Jméno (bez diakritiky)')),
                ('surname_normalized', models.CharField(blank=True, default='', max_length=255, verbose_name='Příjmení (bez diakritiky)')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('year', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Ročník')),
                ('nickname', models.CharField(blank=True, default='', max_length=255, verbose_name='Přezdívka')),
                ('disability', models.CharField(blank=True, default='', max_length=255, verbose_name='Omezení')),
                ('roommate', models.CharField(blank=True, default='', max_length=255, verbose_name='Spolubydlící')),
                ('gdpr_consent', models.BooleanField(default=False, verbose_name='Souhlas s GDPR')),
                ('newsletter_consent', models.BooleanField(default=False, verbose_name='Souhlas s newsletterem')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Zaplaceno')),
                ('is_substitute', models.BooleanField(default=False, verbose_name='Náhradník')),
                ('photo', models.ImageField(blank=True, upload_to='people', verbose_name='Fotka')),
                ('cancel_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token pro zrušení')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.batch', verbose_name='Turnus')),
                ('billing_information', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='reservations.billinginformation', verbose_name='Fakturační údaje')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculties.faculty', verbose_name='Fakulta')),
            ],
            options={
                'verbose_name': 'Rezervace',
                'verbose_name_plural': 'Rezervace',
                'ordering': ['created_at'],
            },
        ),
    ]
