# Generated by Django 5.2.17 on 2026-10-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='registration_closes_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registrace končí'),
        ),
        migrations.AddField(
            model_name='batch',
            name='registration_opens_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registrace začíná'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='capacity',
            field=models.PositiveIntegerField(default=100, verbose_name='Kapacita'),
        ),
    ]
